apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
  labels:
    version: v1
    tier: backend
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-app
          image: prosperibe12/auth-service
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15 
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15