apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  # General settings
  DEBUG: "False"
  ALLOWED_HOSTS: "127.0.0.1,localhost,*"
  ENVIRONMENT: "production"

  # Database configuration
  DB_HOST: "postgres-service"
  DB_USER: "Prosperibe12"
  DB_NAME: "microservices_auth"
  DB_PORT: "5432"
  DB_ENGINE: "django.db.backends.postgresql"

  # Email configuration
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USE_TLS: "True"
  EMAIL_USE_SSL: "False"

  # Admin configuration
  ADMIN_USER_NAME: "Prosperibe12"
  ADMIN_USER_EMAIL: "Prosperibe12@gmail.com"