apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
spec:
  scaleTargetRef:
    name: auth-deploy
    apiVersion: apps/v1
    kind: Deployment
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70 
