apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project.name" . }}-secret 
  labels:
    app: {{ .Values.commonLabels.app }}
    tier: {{ .Values.commonLabels.tier }}
data:
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | b64enc | quote }} 
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }} 
  EMAIL_HOST_PASSWORD: {{ .Values.secret.EMAIL_HOST_PASSWORD | b64enc | quote }} 
  EMAIL_HOST_USER: {{ .Values.secret.EMAIL_HOST_USER | b64enc | quote }}
