name: Auth Service Continuos Integration Pipeline
# This workflow is triggered on pull requests to the master branch
# It ensures that the incoming code is tested before merging to the master branch
on:
  pull_request:
    branches:
      - master
  
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      CLOUD_AMQP_URL: ${{ secrets.CLOUD_AMQP_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      ENVIRONMENT: ${{vars.ENVIRONMENT}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install DB Dependencies
        run: |
          sudo apt install postgresql postgresql-contrib -y 
        shell: bash

      - name: Install Application Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run Migrations
        run: |
          python3 manage.py makemigrations
          python3 manage.py migrate

      - name: Run Tests
        run: |
          echo "Running Tests"
          coverage run manage.py test
          echo "Completed Tests"

      - name: Run Coverage Report
        run: |
          coverage html

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage_html_report
